language: android

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository
    - tools
    - platform-tools

jdk:
  - oraclejdk7

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

script:
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)